### ISSUE TITLE
Can -InputFile or similar parameter be used?

### ISSUE THREAD

**Issue by nojnoj33** [ctigeek/InvokeQueryPowershellModule#1]
Hi, 

Great module, one question, 

With Invoke-Sqlcmd you can specify an imput file e.g. ( -InputFile "\myfile.sql" ) can you do this with your module?

Thanks
Jon

**Comment by ctigeek** [comment]
Hi Jon.
I'm very sorry for the delay in answering.

The "correct" powershell way to do this would be to use `Get-Content` and then you can pipe that directly into the `Invoke-SqlServerQuery` (or other) command.

Hope that helps!
Steve
