### ISSUE TITLE
Bug when using connection string with Invoke-SqlServerQuery 

### ISSUE THREAD

**Issue by Sarafian** [ctigeek/InvokeQueryPowershellModule#10]
**How to reproduce issue**
When I using the `-ConnectionString` parameter with e.g. `Invoke-SqlServerQuery`

```powershell
Invoke-SqlServerQuery -ConnectionString $connectionstring -Sql $sql
```

I get an error 

> Invoke-SqlServerQuery : Object reference not set to an instance of an object.

**Workaround**
Feed the respected values from the connectionstring as separate parameters 

```powershell
Invoke-SqlServerQuery -Server $server -Database $database -Credential $credentials -Sql $sql
```

- Tested on version 1.0.1
- Bug is valid even when using the query item created by `New-SqlQuery` instead of raw sql
- Didn't test with other cmdlets

**Comment by diontools** [comment]
I also found this problem.
Failure to get local instance name when SQL server is not installed on my machine.
I modified to not get the local instance name when ConnectionString is specified.

**Comment by crshovrd41** [comment]
I am also receiving this same error.
